version: 2

run:
  timeout: 5m
  skip-dirs:
    - "vendor"
    - "docs"
    - "bin"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck

linters-settings:
  errcheck:
    exclude-tests: true # игнорировать ошибки в тестах