run:
  timeout: 5m
  skip-dirs:
    - vendor
    - docs
    - bin

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused  # добавил твой предыдущий unused

linters-settings:
  errcheck:
    # exclude-tests больше не поддерживается
    # чтобы игнорировать тесты, используем exclude с регуляркой
    exclude: ".*_test\\.go"

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - errcheck