run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused

linters-settings:
  errcheck: {}

issues:
  exclude-rules:
    # исключаем ошибки errcheck в тестах
    - path: _test\.go
      linters:
        - errcheck
    # исключаем папки vendor, docs, bin
    - path: vendor
    - path: docs
    - path: bin