services:

  redis-service:
    image: redis:8.2.3
    container_name: redis-service
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - project


  kafka-1:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-1
    restart: unless-stopped
    ports:
      - "19092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG4J_LOGGERS: "org.apache.kafka=WARN"
      CLUSTER_ID: "TvgU7WsG0ycedQiZewEdjw"
    volumes:
      - kafka_data_1:/var/lib/kafka/data
    networks:
      - project


  kafka-2:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-2
    restart: unless-stopped
    ports:
      - "29092:9092"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG4J_LOGGERS: "org.apache.kafka=WARN"
      CLUSTER_ID: "TvgU7WsG0ycedQiZewEdjw"
    volumes:
      - kafka_data_2:/var/lib/kafka/data
    networks:
      - project


  kafka-3:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-3
    restart: unless-stopped
    ports:
      - "39092:9092"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG4J_LOGGERS: "org.apache.kafka=WARN"
      CLUSTER_ID: "TvgU7WsG0ycedQiZewEdjw"
    volumes:
      - kafka_data_3:/var/lib/kafka/data
    networks:
      - project


  rabbitmq-service:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-service
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - project


  prometheus-service:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - project


  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    depends_on:
      - loki
    volumes:
      - ./grafana/promtail/positions:/promtail-data                # вместо promtail_data:/promtail-data
      - /var/lib/docker/containers:/var/lib/docker/containers:ro   # для чтения логов конт. напрямую
      - /var/run/docker.sock:/var/run/docker.sock:ro               # для авт. обнаружения контейнеров
      - ./grafana/promtail/config.yml:/etc/promtail/config.yml:ro  # настройки promtail из файла
    command:
      -config.file=/etc/promtail/config.yml
    networks:
      - project


  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    volumes:
      - loki_data:/loki
      - ./grafana/loki/config.yml:/etc/loki/config.yml:ro
    networks:
      - project


  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=MkRV6gnXk4rcY@k
      - GF_LOGS_DESTINATION=loki
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - project


networks:
  project:
    driver: bridge

volumes:
  prometheus_data:
  promtail_data:
  loki_data:
  grafana_data:
  kafka_data_1:
  kafka_data_2:
  kafka_data_3:
  redis_data: