env: "local"

http_server:
  address: "localhost:8080"
  server_shutdown_timeout: 5s
  timeout: 5s # время на чтение запроса / отправку ответа / обработ. - неогр.
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 60s # время жизни соединения с клиентом

auth:
  jwt_secret: "super_secret"
  token_ttl: 1h

services:
  auth_service: "localhost:7971"
  products_service: "localhost:7972"
  users_service: "localhost:7973"
  basket_service: "localhost:7974"
  orders_service: "localhost:7975"
  nots_service: "localhost:7976"