name: Go CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.5"

      - name: Install dependencies
        run: go mod tidy -v

      #- name: Run tests
      #  run: go test ./...

      #- name: Run linter
      #  uses: golangci/golangci-lint-action@v6
        #  with:
        # version: latest
        # args: --timeout=5m

      # Сборка gateway
      - name: Build Gateway Docker image
        run: docker build -t auth-service -f ./gateway/Dockerfile .

      # Сборка auth
      - name: Build Auth Docker image
        run: docker build -t auth-service -f ./auth/Dockerfile .

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker images
        run: |
          docker tag gateway-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/gateway-service:latest
          docker tag auth-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gateway-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest
